/**
 * Mock Data Catalog for Product Discovery & Offline Demonstration
 */

export const CATEGORIES = [
  {
    id: 'cat-1',
    name: 'Electronics',
    slug: 'electronics',
    icon: 'Laptop',
    description: 'Headphones, laptops, smartwatches, and gadgets',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    itemCount: 42,
  },
  {
    id: 'cat-2',
    name: 'Fashion',
    slug: 'fashion',
    icon: 'Shirt',
    description: 'Men & Women apparel, shoes, and luxury accessories',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&q=80',
    itemCount: 88,
  },
  {
    id: 'cat-3',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    icon: 'Home',
    description: 'Cookware, coffee makers, smart home items',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80',
    itemCount: 65,
  },
  {
    id: 'cat-4',
    name: 'Books',
    slug: 'books',
    icon: 'BookOpen',
    description: 'Bestselling fiction, business, tech, and biographies',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
    itemCount: 120,
  },
  {
    id: 'cat-5',
    name: 'Beauty & Care',
    slug: 'beauty',
    icon: 'Sparkles',
    description: 'Skincare, fragrances, and personal grooming',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80',
    itemCount: 54,
  },
  {
    id: 'cat-6',
    name: 'Sports & Outdoors',
    slug: 'sports',
    icon: 'Dumbbell',
    description: 'Fitness equipment, yoga mats, camping gear',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&q=80',
    itemCount: 39,
  },
];

export const PRODUCTS = [
  {
    id: 'prod-101',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    slug: 'sony-wh-1000xm5-wireless-headphones',
    description: 'Industry-leading noise canceling headphones with two processors and 8 microphones for unprecedented noise cancellation.',
    price: 399.99,
    discountPrice: 329.99,
    category: 'Electronics',
    rating: 4.8,
    reviewCount: 1280,
    inventory: 24,
    SKU: 'SNY-WH1000XM5-BLK',
    badgeText: 'Best Seller',
    isFeatured: true,
    isDeal: true,
    seller: { id: 'seller-1', name: 'Sony Direct Store', rating: 4.9 },
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
    ],
    specifications: [
      { key: 'Battery Life', value: 'Up to 30 hours' },
      { key: 'Connectivity', value: 'Bluetooth 5.2' },
      { key: 'Weight', value: '250g' },
      { key: 'Warranty', value: '1 Year Manufacturer' },
    ],
  },
  {
    id: 'prod-102',
    name: 'Apple MacBook Air M3 15-inch',
    slug: 'apple-macbook-air-m3-15-inch',
    description: 'Ultra-thin 15-inch Liquid Retina display powered by M3 chip for exceptional performance and up to 18 hours battery life.',
    price: 1299.00,
    discountPrice: 1149.00,
    category: 'Electronics',
    rating: 4.9,
    reviewCount: 940,
    inventory: 12,
    SKU: 'APL-MBA-M3-15',
    badgeText: 'Choice Product',
    isFeatured: true,
    isDeal: true,
    seller: { id: 'seller-2', name: 'Apple Authorized Store', rating: 5.0 },
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&q=80',
    ],
    specifications: [
      { key: 'Processor', value: 'Apple M3 8-core CPU' },
      { key: 'RAM', value: '16GB Unified Memory' },
      { key: 'Storage', value: '512GB SSD' },
      { key: 'Display', value: '15.3-inch Liquid Retina' },
    ],
  },
  {
    id: 'prod-103',
    name: 'Classics Unisex Organic Cotton Hoodie',
    slug: 'classics-unisex-organic-cotton-hoodie',
    description: 'Premium heavyweight organic cotton fleece hoodie with double-lined hood and relaxed streetwear fit.',
    price: 79.99,
    discountPrice: 59.99,
    category: 'Fashion',
    rating: 4.5,
    reviewCount: 410,
    inventory: 45,
    SKU: 'FSH-HD-ORG-L',
    badgeText: 'Top Fashion',
    isFeatured: false,
    isDeal: true,
    seller: { id: 'seller-3', name: 'Urban Apparel Co', rating: 4.7 },
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80',
    ],
    specifications: [
      { key: 'Material', value: '100% Organic Cotton' },
      { key: 'Fit', value: 'Relaxed Streetwear' },
      { key: 'Care', value: 'Machine Wash Cold' },
    ],
  },
  {
    id: 'prod-104',
    name: 'DeLonghi Magnifica Espresso Machine',
    slug: 'delonghi-magnifica-espresso-machine',
    description: 'Automatic bean-to-cup espresso machine with manual milk frother and customizable grind settings.',
    price: 699.99,
    discountPrice: 549.99,
    category: 'Home & Kitchen',
    rating: 4.7,
    reviewCount: 630,
    inventory: 8,
    SKU: 'HM-DL-MAG-ESP',
    badgeText: 'Top Rated',
    isFeatured: true,
    isDeal: false,
    seller: { id: 'seller-4', name: 'Kitchen & Barware Hub', rating: 4.8 },
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80',
      'https://images.unsplash.com/photo-1517668808822-9ebe02f2a698?w=800&q=80',
    ],
    specifications: [
      { key: 'Pressure', value: '15 Bar Pump' },
      { key: 'Water Tank', value: '1.8 Liters' },
      { key: 'Grinder', value: 'Steel Conical Burrs' },
    ],
  },
  {
    id: 'prod-105',
    name: 'Atomic Habits by James Clear',
    slug: 'atomic-habits-james-clear',
    description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones. Over 15 million copies sold worldwide.',
    price: 27.00,
    discountPrice: 16.99,
    category: 'Books',
    rating: 4.9,
    reviewCount: 3820,
    inventory: 150,
    SKU: 'BK-ATM-HBT-HC',
    badgeText: '#1 Bestseller',
    isFeatured: true,
    isDeal: true,
    seller: { id: 'seller-5', name: 'Bookstore Direct', rating: 5.0 },
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80',
    ],
    specifications: [
      { key: 'Format', value: 'Hardcover' },
      { key: 'Pages', value: '320' },
      { key: 'Publisher', value: 'Avery' },
    ],
  },
  {
    id: 'prod-106',
    name: 'Garmin Forerunner 265 Running Smartwatch',
    slug: 'garmin-forerunner-265-smartwatch',
    description: 'GPS running smartwatch with bright AMOLED display, training metrics, and recovery insights.',
    price: 449.99,
    discountPrice: 399.99,
    category: 'Electronics',
    rating: 4.7,
    reviewCount: 290,
    inventory: 18,
    SKU: 'GRM-FR265-BLK',
    badgeText: 'New Release',
    isFeatured: false,
    isDeal: false,
    seller: { id: 'seller-1', name: 'Sony Direct Store', rating: 4.9 },
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    ],
    specifications: [
      { key: 'Display', value: 'AMOLED Touchscreen' },
      { key: 'Battery', value: 'Up to 13 days in smartwatch mode' },
      { key: 'Water Rating', value: '5 ATM' },
    ],
  },
];
